### ISSUE TITLE
can you give a pbtxt for you light-head-rcnn?

### ISSUE THREAD

**Issue by swearos** [HiKapok/X-Detector#1]
i want to convert you light-head rcnn ckpt to pb,but i don't know the output_name of graph.
can you share the pbtxt for for your light-head-rcnn ckpt?

**Comment by HiKapok** [comment]
I'm sorry for that I didn't try this. I have used custom ops (PsRoIAlign) in my code, so even if the pbtxt is given, you should also compile TensorFlow from source with this new op. Maybe this [link](https://stackoverflow.com/questions/43880729/using-new-op-while-importing-graph-in-tensorflow) is helpful

**Comment by HiKapok** [comment]
hi, *.pbtxt is now available in that google drive shared link.
