### ISSUE TITLE
I want to train/test xception model with light_head_rfcn_train.py, can you Provide a simple script？

### ISSUE THREAD

**Issue by lxyyang** [HiKapok/X-Detector#2]
I want to train/test xception model with light_head_rfcn_train.py, can you Provide a simple script？
thank you very much

**Comment by HiKapok** [comment]
You can just change the 'data_dir'and 'checkpoint_path' according to your local directory, and the 'checkpoint_path' is the pretrained xception weights, you can find [here](https://github.com/HiKapok/Xception_Tensorflow). Before you start training you should also set 'run_on_cloud' to False.

**Comment by HiKapok** [comment]
as for creating *.tfrecords, just follow this [file](https://github.com/HiKapok/X-Detector/blob/master/dataset/convert_pascalvoc_to_tfrecords.py). change the dataset path at the bottom of that file and run to generate the 2007 or 2012 dataset in tfrecords. If you have other problems please let me know, thank you!
