### ISSUE TITLE
Questions about the light_head_rfcn_train.py

### ISSUE THREAD

**Issue by KevinWalkerFan** [HiKapok/X-Detector#4]
I'm trying to run the light_head_rfcn_train.py but I get the error below. It shows that package 'tf_extended' doesn't exist. 

![error1](https://user-images.githubusercontent.com/26733530/41913538-28a529b8-7983-11e8-8579-a40ddddb817e.JPG)

**Comment by HiKapok** [comment]
@KevinWalkerFan  I'm sorry, please comment that line and try again

**Comment by KevinWalkerFan** [comment]
I tested the code on Tensorflow 1.6.0, Python 3.5, **Windows 10**

**Comment by KevinWalkerFan** [comment]
I tried to comment that line but new errors comes out. Maybe it's the difference between the Ubuntu and Windows.

![error2](https://user-images.githubusercontent.com/26733530/41922874-aa4031e2-7998-11e8-9732-9ad739352e07.JPG)

**Comment by HiKapok** [comment]
@KevinWalkerFan I did not test this op under Windows, but at least the suffix of the library should not be '*.so'

**Comment by KevinWalkerFan** [comment]
Thank u. And Do I need the PsRoIAlign that u mentioned? I didn't use it.

**Comment by HiKapok** [comment]
@KevinWalkerFan yes, the proposals must be pooled into the same.size before feed into rcnn
